<?php
// $Id$

/**
 * Main user validation function.
 *
 * If successful, sets the global $user object
 */
function htpasswd_login_authenticate_validate($form, &$form_state) {
  htpasswd_authenticate($form_state['values']);
}

/**
 * Main user authentication function.
 *
 * If successful, sets the global $user object.
 */
function htpasswd_authenticate($form_values = array()) {
  print_r($form_values);
}

/**
 * Implements hook_form_alter().
 */
function htpasswd_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['#validate']) && is_array($form['#validate']) && ($key = array_search('user_login_authenticate_validate', $form['#validate'])))
    $form['#validate'][$key] = 'htpasswd_login_authenticate_validate';
}
